### ISSUE TITLE
Fluids: Cleanup/Todos from #1264

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#1267]
Cleanup tasks discovered in #1264 , but not directly related to that PR.

 - [x] Fix issues stemming from https://github.com/CEED/libCEED/pull/1269
     - To be done in that PR
 - [x] Implement equivalent of `RatelCeedCall` to catch Ceed error messages with Petsc (#1275)
 - [x] Don't use `GetRestrictionForDomain` for every restriction
 - [x] Add helper function for setting up `PetscFE` for auxillary DMs (#1308)
 - [x] Create new QF for getting surface data for strong bcs (#1303)
     - Mostly, don't have a `weight` field when I don't need it: https://github.com/CEED/libCEED/blob/33668f5287e5e80c959055d310dc82aaa45e0803/examples/fluids/src/strong_boundary_conditions.c#L76-L79
- [x] Split `Setup2d`, `Setup3d`, etc. into QF helpers for inverse mapping jacobian and wdetj separately
    - This would address this PR comment: https://github.com/CEED/libCEED/pull/1269#discussion_r1279710463
    - Addressed in #1303 
- [x] Remove `qdata` arg from ICs
- [x] Update log data grabbing to reflect new PETSc version (#1297)
