### ISSUE TITLE
Benchmark Paper

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#395]
We've discussed making a libCEED benchmark paper, especially in light of @YohannDudouit's fantastic `gpu/cuda/gen` performance. Here are some prereq ToDos:

- Benchmark Codes
- [x] Add CUDA Vecs to PETSc BPs #294
- [ ] Improve MFEM example for benchmarking (CUDA seems to do better there currently) #325

- CPU
- [ ] AVX 512 gather/scatter for ElemRestriction (Current botteneck)
- [ ] New LIBXSMM kernels
- [ ] Even/Odd decomposition for BasisApply? Would require intermediate data movement

- GPU
- [ ] OCCA backend overhaul (Would give us a chance to see if OCCA offers fast HIP, OCL, etc) #305
