### ISSUE TITLE
Solid Mechanics Development Roadmap

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#814]
This issue lists tasks/PRs in our planned roadmap for the solid mechanics mini-app. When the app moves to a new repo, this issue should go to the new repo. What am I missing in the list?

Direct Application Development:
- [ ] multi-materiel support
- [ ] load increment improvement (#710)
- [ ] elastodynamics solver
- [ ] inelastic materials
- [ ] contact
- [ ] wall friction
- [ ] materiel point model

libCEED Core Development:
- [ ] kernel caching (#805)
 
PETSc Development:
- [ ] build operator from DMPlex + some extra data
- [ ] GPU sparse assembly support (see https://gitlab.com/petsc/petsc/-/merge_requests/4293)

**Comment by jedbrown** [comment]
@karenlstengel is working on multi-material. The load increments work can be done here or directly in PETSc. (We'd use a simpler model problem to test it there.) There are lots of additional mechanics like inelastic materials, contact, wall friction, and MPM that will go in the new repository (way out of scope for whatever stays here).

**Comment by jeremylt** [comment]
Moved to https://gitlab.com/micromorph/ratel/-/issues
